---
- name: Install flannel overlay network package
  yum: 
    name: flannel
    state: latest

- name: Create a directory for etcd certs
  file: 
    path: /etc/ssl/etcd 
    state: directory

- name: Copy etcd certificate.
  copy:
    src: etcd-certs/
    dest: /etc/ssl/etcd/
    force: yes

- name: Configure flannel
  template: 
    src: flanneld.j2 
    dest: /etc/sysconfig/flanneld

- name: Enable and start flanneld
  service: 
    name: flanneld 
    state: restarted 
    enabled: yes
...
